export type ContentBlock =
  | { type: 'text'; text: string }
  | {
      type: 'image';
      source: {
        type: 'base64';
        media_type: 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp';
        data: string;
      };
      /** Durable identity used to reinspect the image after checkpoint/restart. */
      filePath?: string;
      attachmentRef?: string;
      dimensions?: { width: number; height: number };
    };

export type ProviderContentBlock = Record<string, unknown> & { type: string };
export type ProviderApiType = 'anthropic-messages' | 'openai-chat-completions' | 'openai-responses';

export type ContextLifecycle = 'session' | 'episode' | 'call';
export type ContextCacheScope = 'stable' | 'epoch' | 'volatile';
export type ContextPersistence = 'durable' | 'transient';
export type ContextPlacement = 'instruction_prefix' | 'transcript' | 'request_tail';
export type ContextRetention = 'append' | 'replace' | 'request';
export interface ContextEventIdentity {
  id: string;
  part: number;
  parts: number;
}
export type ContextSource =
  | 'runtime_context'
  | 'runtime_target_rules'
  | 'runtime_observation_rules'
  | 'runtime_feedback'
  | 'runtime_transient'
  | 'plan_status'
  | 'goal_status'
  | 'subagent_status'
  | 'skills_list'
  | 'current_directory'
  | 'runner_hint'
  | 'pending_user_input'
  | 'synthetic_observation'
  | 'compaction_boundary'
  | 'compaction_instruction'
  | 'compaction_summary'
  | 'tool_result_prune'
  | 'provider_recovery';

/** Internal context lifecycle metadata. Provider serializers never emit it. */
export interface ContextLifecycleAnnotation {
  schema: 'xiaoba.context_lifecycle.v1';
  source: ContextSource;
  lifecycle: ContextLifecycle;
  cacheScope: ContextCacheScope;
  persistence: ContextPersistence;
  /** Provider-neutral placement semantics; serializers still choose the wire representation. */
  placement?: ContextPlacement;
  /** Whether later requests append, replace, or discard this context item. */
  retention?: ContextRetention;
  /** Internal idempotency identity for a multi-message context event. Never sent to providers. */
  event?: ContextEventIdentity;
  /** Raw epoch identity stays in memory; telemetry exposes only a fingerprint. */
  epoch?: string;
}

/** Opaque scope that prevents provider-only replay state crossing model/API boundaries. */
export interface ProviderStateReference {
  schema: 'xiaoba.provider_state.v1';
  apiType: ProviderApiType;
  model: string;
  endpointFingerprint: string;
}

/** Durable identity for a media artifact that must be re-opened after compaction. */
export interface CheckpointArtifactIdentity {
  kind: 'image';
  mediaType: string;
  encodedBytes: number;
  sha256: string;
  filePath?: string;
  attachmentRef?: string;
  dimensions?: { width: number; height: number };
  sourceRole: Message['role'];
  sourceName?: string;
  sourceToolCallId?: string;
}

export type ReasoningEffort = 'default' | 'none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max' | 'disabled';
export type OpenAIApiMode = 'chat_completions' | 'responses';

export interface Message {
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string | ContentBlock[] | null;
  tool_calls?: Array<{
    id: string;
    type: 'function';
    function: {
      name: string;
      arguments: string;
    };
  }>;
  tool_call_id?: string;
  name?: string;
  /** 标记由 injectContext 注入的消息，用于滑动窗口清理 */
  __injected?: boolean;
  /**
   * Provider-only cache placement hint. Dynamic system context remains system-priority
   * but is appended to Responses input instead of destabilizing instructions.
   */
  __cacheScope?: 'stable' | 'dynamic';
  /** Typed replacement for prefix/boolean-based transient and cache conventions. */
  __context?: ContextLifecycleAnnotation;
  /** 标记注入给 agent 看的运行时反馈，仅供内部清理和日志记录使用 */
  __runtimeFeedback?: boolean;
  /** 标记内部 runtime observation，例如子 agent 完成结果；对模型仍以 user role 承载 */
  __runtimeObservation?: boolean;
  runtimeObservationSource?: string;
  /** 标记内部错误占位，仅用于本地恢复/继续，不应进入模型上下文或持久历史。 */
  __internalErrorArtifact?: boolean;
  /** Synthetic tool-call/tool-result pair used as transient runtime context. */
  __syntheticObservation?: boolean;
  syntheticObservationId?: string;
  /** Internal branch provenance for evidence correlation. Never sent to providers. */
  syntheticObservationProvenance?: {
    branchType: string;
    branchId: string;
  };
  /** Internal episode marker used for local compaction grouping. Never sent to providers. */
  __episodeId?: string;
  /** Distinguishes the initial user input from user messages merged while a turn is running. */
  __episodeInputKind?: 'root' | 'pending';
  /** Durable continuation checkpoint generated by the main Agent compaction chain. */
  __checkpointSummary?: boolean;
  /** Durable marker for a continuation checkpoint boundary. */
  __checkpointBoundary?: boolean;
  /** Local result state retained only to distinguish completed success from retryable failure. */
  __toolResultState?: {
    status: 'success' | 'failure' | 'unknown';
    retryable: boolean;
  };
  /** Marks an internally derived, canonical completed-tool witness. */
  __checkpointCompletedToolWitness?: true;
  /** Durable local MAC proving the witness was derived by the checkpoint runtime. */
  __checkpointCompletedToolWitnessProvenance?: {
    schema: 'xiaoba.checkpoint_completed_tool_witness.v1';
    episodeId: string;
    keyIdSha256: string;
    macSha256: string;
  };
  /** Deterministic completed-tool ledger propagated across continuation checkpoints. */
  __checkpointCompletedToolCalls?: Array<{
    toolName: string;
    toolCallId: string;
    argumentsSha256: string;
    resultStatus: 'success' | 'failure' | 'unknown';
    retryable: boolean;
  }>;
  /** Internal compaction phase. Never sent to providers. */
  __checkpointPhase?: 'pre_turn' | 'mid_turn' | 'restore';
  /** Deterministic media identities represented by this checkpoint. */
  __checkpointArtifacts?: CheckpointArtifactIdentity[];
  /** 远端耐久上下文来源和消息序号，用于游标写盘失败后的幂等补拉。 */
  __remoteContextSource?: string;
  __remoteContextId?: number;
  /** 压缩后仍被当前 transcript 表示的远端消息高水位；不发送给 provider。 */
  __remoteContextWatermarks?: Record<string, number>;
  /** Durable context event IDs represented by a compaction checkpoint. Never sent to providers. */
  __contextEventIds?: string[];
  /** Provider 原始 assistant content blocks，仅用于下次请求回放，不展示给用户。 */
  providerContent?: ProviderContentBlock[];
  /** Identity of the provider boundary that produced providerContent. Never sent verbatim. */
  providerState?: ProviderStateReference;
}

export interface ChatConfig {
  apiKey?: string;
  apiUrl?: string;
  model?: string;
  temperature?: number;
  maxTokens?: number;
  contextWindowTokens?: number;
  reasoningEffort?: ReasoningEffort;
  openaiApiMode?: OpenAIApiMode;
  /** Capability facts supplied by the selected model catalog, when available. */
  modelCapabilities?: {
    vision?: boolean;
    toolCalling?: boolean;
    streaming?: boolean;
    /** Endpoint capability; never inferred from a relay hostname. */
    promptCaching?: 'automatic' | 'openai-key' | 'openai-explicit';
  };
  provider?: 'openai' | 'anthropic';
  feishu?: {
    appId?: string;
    appSecret?: string;
    sessionTTL?: number;
    botOpenId?: string;
    botAliases?: string[];
  };
  catscompany?: {
    serverUrl?: string;
    apiKey?: string;
    httpBaseUrl?: string;
    sessionTTL?: number;
  };
  weixin?: {
    token?: string;
    baseUrl?: string;
    cdnBaseUrl?: string;
    allowFrom?: string[];
    sessionTTL?: number;
    longPollTimeout?: number;
  };
  catscoLogUpload?: {
    enabled?: boolean;
    serverUrl?: string;
    intervalMinutes?: number;
  };
}

/** Exact provider response field that supplied cachedReadTokens. */
export type ProviderCacheReadSource =
  | 'openai.input_tokens_details.cached_tokens'
  | 'openai.prompt_tokens_details.cached_tokens'
  | 'deepseek.prompt_cache_hit_tokens'
  | 'anthropic.cache_read_input_tokens';

/** Allowlisted projection of exact numeric provider usage fields. */
export type ProviderReportedUsage =
  | {
      contract: 'openai-responses-v1';
      input_tokens?: number;
      cached_tokens?: number;
      cache_write_tokens?: number;
    }
  | {
      contract: 'openai-chat-v1';
      prompt_tokens?: number;
      cached_tokens?: number;
      cache_write_tokens?: number;
    }
  | {
      contract: 'deepseek-chat-v1';
      prompt_tokens?: number;
      prompt_cache_hit_tokens?: number;
    }
  | {
      contract: 'anthropic-messages-v1';
      input_tokens?: number;
      cache_read_input_tokens?: number;
      cache_creation_input_tokens?: number;
    };

export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  /** True only when the provider explicitly reports the input-token component(s). */
  inputTokensReported?: boolean;
  /** Present only when the provider explicitly reports cache-read usage. */
  cachedReadTokens?: number;
  /** Present only with cachedReadTokens; never inferred from endpoint/model names. */
  cacheReadSource?: ProviderCacheReadSource;
  /** Present only when the provider explicitly reports cache-write usage. */
  cachedWriteTokens?: number;
  /** Exact allowlisted raw fields used by strict benchmark evidence. */
  providerUsage?: ProviderReportedUsage;
}

export interface ChatResponse {
  content: string | null;
  toolCalls?: Array<{
    id: string;
    type: 'function';
    function: {
      name: string;
      arguments: string;
    };
  }>;
  usage?: TokenUsage;
  /** Provider stop/finish reason, e.g. max_tokens/length/tool_use/stop. */
  stopReason?: string;
  /** Provider 原始 assistant content blocks，仅用于下次请求回放，不展示给用户。 */
  providerContent?: ProviderContentBlock[];
  /** Identity of the provider boundary that produced providerContent. Never sent verbatim. */
  providerState?: ProviderStateReference;
}

export interface CommandOptions {
  interactive?: boolean;
  message?: string;
  config?: string;
  skill?: string;
}

// 导出 Agent 相关类型
export * from './agent';
export * from './tool';
export * from './skill';
export * from './session-identity';
